attribute-types:
  http://www.w3.org/2001/XMLSchema#string:
    alias: string
    class: Xillion\Core\AttributeType\Xml\StringType
    description: Regular string
  http://www.w3.org/2001/XMLSchema#integer:
    alias: integer
    class: Xillion\Core\AttributeType\Xml\IntegerType
    description: Regular integer

attribute-definitions:
  urn:oasis:names:tc:xacml:1.0:subject:subject-id:
    type: http://www.w3.org/2001/XMLSchema#string
    description: Is the name of the user as required by Health Insurance Portability and Accountability Act (HIPAA) Privacy Disclosure Accounting. The name will be typed as a string and in plain text.
  urn:oasis:names:tc:xacml:1.0:subject:group:
    type: http://www.w3.org/2001/XMLSchema#string
  urn:oasis:names:tc:xacml:1.0:resource:resource-id:
    type: http://www.w3.org/2001/XMLSchema#string
    description: Unique identifier of the resource defined by and controlled by the servicing organization. In healthcare this is the patient unique identifier.
  http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname:
    type: http://www.w3.org/2001/XMLSchema#string
  http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress:
    type: http://www.w3.org/2001/XMLSchema#string
  http://linkorb.com/attributes/ubid:
    type: http://www.w3.org/2001/XMLSchema#string
  http://linkorb.com/attributes/group:
    type: http://www.w3.org/2001/XMLSchema#string

resource-types:
  https://linkorb.com/attributes/resource-types/card:
    description: Describes a card
    attribute-definitions:
      - urn:oasis:names:tc:xacml:1.0:subject:subject-id
      - urn:oasis:names:tc:xacml:1.0:resource:resource-id
  https://linkorb.com/attributes/resource-types/user:
    description: Describes a user
    attribute-definitions:
      - http://linkorb.com/attributes/ubid
      - http://linkorb.com/attributes/group

resources:
  alice:
    types:
      - https://linkorb.com/attributes/resource-types/user
    attributes:
      http://linkorb.com/attributes/ubid: alice
      http://linkorb.com/attributes/group: []
      urn:oasis:names:tc:xacml:1.0:subject:subject-id: alice
      urn:oasis:names:tc:xacml:1.0:resource:resource-id: cool
  bob:
    types:
      - https://linkorb.com/attributes/resource-types/user
    attributes:
      http://linkorb.com/attributes/ubid: bob
      http://linkorb.com/attributes/group: []
      urn:oasis:names:tc:xacml:1.0:subject:subject-id: bob
      urn:oasis:names:tc:xacml:1.0:resource:resource-id: yeah
